### ISSUE TITLE
Document currently used features of Sauce

### ISSUE THREAD

**Issue by DanielBrierton** [RaspberryPiFoundation/sauce-design-system#77]
## Readiness 🚀
 🟠 What we are waiting on:
- Refinement

## Linked Issues 🏷️
Is this part of a bigger piece of work?

## User Story 📗
As a user of Sauce I want the features I currently use to be included in the new design system So that I have a clear upgrade path

## Description 👀
We want to get an idea of what features of sauce@next are actually being used so we can use them as a base for our new design system library. My hope would be that we can basically copy/paste these features wholesale, although some may need tweaking if they're opinionated in terms of sizing/colour.

The following repos use `next` so can be compared directly
* https://github.com/RaspberryPiFoundation/astro-pi-registration
* https://github.com/RaspberryPiFoundation/coderdojo-frontend
* https://github.com/RaspberryPiFoundation/projects-ui

These don't use `next`, so some level of mapping their usage of `v1.0.0-alpha.9` to features that exist in `next`
* https://github.com/RaspberryPiFoundation/PageKit
* https://github.com/RaspberryPiFoundation/showcase
* https://github.com/RaspberryPiFoundation/astro-pi.org-2020 (uses `v1.0.0-alpha.9`)

This documentation can be done via comment(s) on this issue.

## Tasks ✨
- [ ] *Add tasks here...*
- [ ] Add/update tests
- [ ] Check on mobile, tablet, desktop

## Assets 🔗
| Asset | Link |
| ----- | ----- |
| Design | .... |
| Copy | .... |
